Insert into VENSECURITYTYPE (CODE, DESCRIPTION, CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, VERSION) VALUES ('BASICAUTH','BasicAuth', 'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 1);
Insert into VENSECURITYTYPE (CODE, DESCRIPTION, CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, VERSION) VALUES ('CERTIFY','Certify', 'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 1);

Insert into GLBSTATUS (CODE, DESCRIPTION, CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, VERSION) VALUES ('ACTIVE','Active', 'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 1);
Insert into GLBSTATUS (CODE, DESCRIPTION, CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, VERSION) VALUES ('INACTIVE','Inactive', 'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 1);
Insert into GLBSTATUS (CODE, DESCRIPTION, CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, VERSION) VALUES ('CERTIFY','Certify', 'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 1);
Insert into GLBSTATUS (CODE, DESCRIPTION, CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, VERSION) VALUES ('PENDING','Pending',  'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 1);
commit;